apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.Namespacename }}
  name: {{ .Values.Servicename }}
  labels:
    app.kubernetes.io/managed-by: Helm

spec:
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
  type: NodePort
  selector:
    {{- toYaml .Values.selector| nindent 4 }}
